CREATE TABLE "member" (
  "member_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "name" varchar(50) NOT NULL,
  "phone" varchar(20) NOT NULL,
  "role" "enum(USER,HOST,ADMIN)" NOT NULL DEFAULT 'USER',
  "status" "enum(ACTIVE,SUSPENDED,DELETED)" NOT NULL DEFAULT 'ACTIVE',
  "created_at" timestamp
);

CREATE TABLE "member_point_history" (
  "point_history_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" bigint NOT NULL,
  "amount" int NOT NULL,
  "type" "enum(EARN,USE)" NOT NULL,
  "description" varchar(200),
  "created_at" timestamp
);

CREATE TABLE "accommodation_category" (
  "category_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "accommodation" (
  "accommodation_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "host_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  "name" varchar(100),
  "price" bigint,
  "description" text,
  "address" varchar(200),
  "latitude" decimal,
  "longitude" decimal,
  "check_in_time" time,
  "check_out_time" time,
  "status" "enum(OPEN,CLOSED)",
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "accommodation_policy" (
  "accommodation_id" bigint NOT NULL,
  "policies" json NOT NULL
);

CREATE TABLE "accommodation_image" (
  "accommodation_id" bigint NOT NULL,
  "image_url" varchar(500),
  "sort_order" int
);

CREATE TABLE "reservation" (
  "reservation_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" bigint NOT NULL,
  "room_id" bigint NOT NULL,
  "check_in_date" date,
  "check_out_date" date,
  "total_price" decimal,
  "status" "enum(RESERVED,CANCELLED,COMPLETED)",
  "reservated_at" timestamp
);

CREATE TABLE "payment" (
  "payment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" bigint UNIQUE NOT NULL,
  "payment_method" "enum(CARD,ACCOUNT_TRANSFER,KAKAO_PAY)",
  "amount" decimal,
  "status" "enum(READY,PAID,FAILED,REFUNDED)",
  "paid_at" timestamp
);

CREATE TABLE "review" (
  "review_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_id" bigint UNIQUE NOT NULL,
  "member_id" bigint NOT NULL,
  "rating" tinyint,
  "content" text,
  "created_at" timestamp
);

CREATE TABLE "review_image" (
  "image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "review_id" bigint NOT NULL,
  "image_url" varchar(500)
);

CREATE TABLE "wishlist" (
  "member_id" bigint NOT NULL,
  "accommodation_id" bigint NOT NULL
);

ALTER TABLE "member_point_history" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");

ALTER TABLE "wishlist" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");

ALTER TABLE "accommodation" ADD FOREIGN KEY ("host_id") REFERENCES "member" ("member_id");

ALTER TABLE "accommodation" ADD FOREIGN KEY ("category_id") REFERENCES "accommodation_category" ("category_id");

ALTER TABLE "accommodation_policy" ADD FOREIGN KEY ("accommodation_id") REFERENCES "accommodation" ("accommodation_id");

ALTER TABLE "accommodation_image" ADD FOREIGN KEY ("accommodation_id") REFERENCES "accommodation" ("accommodation_id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");

ALTER TABLE "payment" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservation" ("reservation_id");

ALTER TABLE "review" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservation" ("reservation_id");

ALTER TABLE "review" ADD FOREIGN KEY ("member_id") REFERENCES "member" ("member_id");

ALTER TABLE "review_image" ADD FOREIGN KEY ("review_id") REFERENCES "review" ("review_id");

ALTER TABLE "accommodation" ADD FOREIGN KEY ("accommodation_id") REFERENCES "reservation" ("room_id");

ALTER TABLE "accommodation" ADD FOREIGN KEY ("accommodation_id") REFERENCES "wishlist" ("accommodation_id");
